import type { Metadata } from "next";
import Link from "next/link"; // Importing Link for navigation
import localFont from "next/font/local";
import "./globals.css";

// Loading local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Page metadata for SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navigation bar */}
        <nav style={{ padding: "10px", background: "#f0f0f0" }}>
          <ul style={{ listStyle: "none", display: "flex", gap: "20px" }}>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/application">Application Form</Link>
            </li>
            <li>
              <Link href="/landing">Landing Page</Link>
            </li>
          </ul>
        </nav>

        {/* Rendering child components */}
        <main>{children}</main>
      </body>
    </html>
  );
}
